#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace attribute_evaluator_device { class U_SolarisSignatureFunctionOuter; }

namespace VersePlayspace_0 { struct Ftuple_L_R; }

namespace VerseInput_0 { class U_SolarisSignatureFunctionOuter; }

namespace SettingEntryBackground_0 { class USettingEntryBackground_C; }

namespace channel_device { class U_SolarisSignatureFunctionOuter; }

namespace mutator_zone_device { class U_SolarisSignatureFunctionOuter; }

namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace VerseAINavigation { struct Ftuple_L_R; }

namespace lock_device { class U_SolarisSignatureFunctionOuter; }

namespace Face_PostProcess_AnimBP { struct FAnimBlueprintGeneratedConstantData; }

namespace item_shop_mannequin_device { class U_SolarisSignatureFunctionOuter; }

namespace VerseGameplayTags { struct Ftuple_L_R; }

namespace VerseFortniteGameScript_FortSceneObject { class U_SolarisSignatureFunctionOuter; }

namespace EpicGamesEngineRestricted { struct Ftuple_L_R; }

namespace Transient { struct FAnimBlueprintGeneratedConstantData; }

namespace VerseQueryTestSuite { struct Ftuple_L_R; }

namespace VerseWorldPartition_0 { struct Ftuple_L_R; }

namespace SettingEntryBackground { class USettingEntryBackground_C; }

namespace zipline_device { class U_SolarisSignatureFunctionOuter; }

namespace character_transformation_device { class U_SolarisSignatureFunctionOuter; }

namespace customizable_color_light_device { class U_SolarisSignatureFunctionOuter; }


namespace class_selector_ui_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseFramework_device_event_optional_agent_handler_mock
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseFramework_test_runner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Llog__level_M_Kchar_R;
}

namespace prop_o_matic_manager_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace prop_manipulator_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace NexusFramework_nexus_test_runner
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace damage_volume_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace wildlife_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace score_manager_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lagent_Mint_R;
	struct Ftuple_L_R;
}

namespace supply_drop_spawner_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace customizable_light_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace EpicGamesTemporary_0
{
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	struct Ftuple_Lvector3_Mvector3_Mfloat_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_Lrotation_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_L_R;
	class U_Root;
	struct Ftuple_Lany_Many_R;
	struct Ftuple_Lfloat_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lrotation_Mrotation_R;
	struct Ftuple_Lvector2i_Mvector2i_R;
}

namespace capture_area_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace switch_device
{
	struct Ftuple_Lagent_Mfloat_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseFortniteGameScript_fort_playspace_player_helper
{
	struct Ftuple_L_R;
	struct Ftuple_Lplayer_Mlogic_Mlogic_Mlogic_R;
	struct Ftuple_Lplayer_Mfort__item__definition_Mint_Mlogic_R;
	struct Ftuple_Lplayer_Mplayer_R;
	struct Ftuple_Lplayer_MPlayerAttribute_MPlayerAttributeOperation_Mfloat_R;
	struct Ftuple_Lplayer_MPlayerAttribute_R;
	struct Ftuple_Lplayer__component_Mplayer__start__component_R;
	struct Ftuple_Lplayer_Mplayer__team_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lplayer_Mlogic_R;
	struct Ftuple_Lvk__component_Mtype_Lvk__component_M_20vk__component_R_R;
}

namespace NexusFramework_example_nexus_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_Mlogic_M_Kchar_R;
}

namespace emote_controller_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseFramework_test_runner
{
	struct Ftuple_L_Kany_Mtuple_L_R_Many_R;
	struct Ftuple_Lvector3_Mvector3_Mfloat_R;
	struct Ftuple_L_R;
	struct Ftuple_L_Kchar_M_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_Lrotation_Mrotation_R;
	struct Ftuple_Llog__level_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_Kchar_M_Kchar_M_Kchar_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_R;
}

namespace Entity_0
{
	struct Ftuple_Lentity_Mtuple_L_R_Mtuple_L_R_R;
	class U_Root;
	struct Ftuple_L_R;
}

namespace VerseFramework_device_event_agent_int_handler_mock
{
	struct Ftuple_Lagent_Mint_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace service_station_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VersePrint
{
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
	class U_Root;
}

namespace Component_0
{
	struct Ftuple_Lsupertype_Lany_R_M_Kchar_R;
	struct Ftuple_Laccessor_Mlogic_R;
	struct Ftuple_L_Kany_Mtuple_L_R_Mint_R;
	class U_SolarisSignatureFunctionOuter;
	class U_Root;
	struct Ftuple_L_Kany_Mtuple_L_R_Many_R;
	struct Ftuple_L_R;
	struct Ftuple_Laccessor_Mfloat_R;
	struct Ftuple_Lwidget_Mplayer__ui__slot_R;
}

namespace item_remover_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Verse
{
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_L_Kany_Mtuple_L_R_Mint_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lint_Mint_R;
	struct Ftuple_Lany_Many_R;
	struct Ftuple_L_Kany_Mtuple_L_R_Many_R;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lint_Mint_Mint_R;
}

namespace VerseFortniteGameScript_FortModel
{
	struct Ftuple_Ltransform_M_Kchar_R;
	struct Ftuple_Ltransform_M_Kchar_Mmesh_Mmaterial_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Llogic_Mlogic_R;
	struct Ftuple_Ltransform_M_Kchar_Mmesh_R;
}

namespace VersePrototypeGameplay
{
	struct Ftuple_L_Knav__grid__node__2d_Mnav__grid__node__2d_R;
	struct Ftuple_L_Ksubtype_Lvk__component_R_Mtransform_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Lvector3_Mrotation_Mvector3_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Ltransform_M_Kchar_R;
	struct Ftuple_Lnav__grid__node__2d_M_Knav__grid__node__2d_R;
	struct Ftuple_Lvector3_Mrotation_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_L_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lvector2i_Mvector2i_R;
	struct Ftuple_Ltransform_M_Kchar_Mmesh_R;
	struct Ftuple_Lvector3_M_Kchar_Mmesh_Mmaterial_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Ksubtype_Lvk__component_R_Mtransform_M_Kchar_Mmesh_R;
	struct Ftuple_L_Ksubtype_Lvk__component_R_Mvector3_Mrotation_Mvector3_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Llogic_Mlogic_R;
	struct Ftuple_Ltransform_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Lvk__entity_M_Ksubtype_Lvk__component_R_R;
}

namespace tracker_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lagent_Mint_R;
	struct Ftuple_L_R;
	struct Ftuple_Lint_Mint_R;
}

namespace player_reference_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseFortniteGameScript_fort_game_script_base
{
	struct Ftuple_L_R;
	struct Ftuple_Lvector3_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_R;
	struct Ftuple_Lvk__component_Mtype_Lvk__component_M_20vk__component_R_R;
}

namespace VerseFortnite_0
{
	struct Ftuple_L_Kchar_M_Kchar_M_Kchar_R;
	struct Ftuple_Lteleport__to__result_Mtransform_R;
	struct Ftuple_Laccessor_Mlogic_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_Lentity_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Laccessor_Mfloat_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lnavigation__target_M_QMovementType_Nmovement__type_20_3d_20_2e_2e_2e_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lnpc__behavior_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_Mrotation_R;
}

namespace CompanionAI_0
{
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lnpc__behavior_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_Lvector3_Mfloat_Mfloat_R;
	struct Ftuple_Lfort__character_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_L_Kchar_M_Kchar_M_Kchar_M_Kchar_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_Lagent_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_L_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lagent_Mfloat_Mfloat_R;
	struct Ftuple_Lentity_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lnavigation__target_M_QMovementType_Nmovement__type_20_3d_20_2e_2e_2e_M_QReachRadius_Nfloat_20_3d_20_2e_2e_2e_M_QAllowPartialPath_Nlogic_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Lvector3_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R;
}

namespace explosive_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseEngine_0
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lvk__component_Msupertype_Lany_R_R;
}

namespace VerseFramework_test_device_event_handler_mock
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace UnrealEngineExperimental_0
{
	struct Ftuple_L_R;
	struct Ftuple_Lvector3_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_Mtest__result_M_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R;
}

namespace VGameplayRst_0
{
	struct Ftuple_Lfloat_Mfloat_R;
	struct Ftuple_Lvector3_M_Kchar_R;
	struct Ftuple_Ltransform_M_Kchar_R;
	struct Ftuple_Lvk__entity_M_Ksubtype_Lvk__component_R_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lvector3_Mvector3_R;
	struct Ftuple_L_Ksubtype_Lvk__component_R_Mtransform_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Lvk__component_Msupertype_Lany_R_R;
	struct Ftuple_Ltransform_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Ltransform_M_Kchar_Mmesh_R;
	struct Ftuple_L_R;
	struct Ftuple_L_Ksubtype_Lvk__component_R_Mtransform_M_Kchar_Mmesh_R;
	struct Ftuple_L_Ksubtype_Lvk__component_R_Mvector3_Mrotation_Mvector3_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Llogic_Mlogic_R;
	struct Ftuple_Lrotation_Mtuple_L_R_Mtuple_L_R_R;
	struct Ftuple_Lvector3_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Lvector3_Mrotation_M_Kchar_Mmesh_Mmaterial_R;
	struct Ftuple_Lvector3_Mrotation_Mvector3_M_Kchar_Mmesh_Mmaterial_R;
}

namespace automated_turret_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace creature_placer_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace prop_mover_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseFramework_device_event_ai_interaction_handler_mock
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VersePrototypeGameplay_model_advanced
{
	struct Ftuple_L_R;
	struct Ftuple_Lvector3_Mvector3_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseColors
{
	struct Ftuple_Lint_Mint_Mint_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lfloat_Mfloat_Mfloat_R;
}

namespace post_process_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace hud_message_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseRestricted
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace billboard_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseQuery_0
{
	class U_Root;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lentity_Mtuple_L_R_Mtuple_L_R_R;
}

namespace gameplay_controls_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace fuel_pump_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace vine_rail_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace bouncer_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace crash_pad_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace collectible_object_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace damage_amplifier_powerup_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace item_shop_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace health_powerup_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace creature_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace vfx_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace class_and_team_selector_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace storm_controller_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lvector3_Mrotation_R;
	struct Ftuple_Lvector3_Mrotation_Mfloat_R;
	struct Ftuple_L_R;
	struct Ftuple_Ltransform_Mfloat_R;
}

namespace rng_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseFramework_device_event_optional_agent_int_handler_mock
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace item_placer_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace HeadMovementIK_Proc_CtrlRig
{
	class URigVMMemory_Work;
	class URigVMMemory_Literal;
}

namespace player_marker_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseDevices
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_R;
	struct Ftuple_L_R;
	struct Ftuple_Lrotation_Mrotation_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_Ltransform_Mfloat_R;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_Lteleport__to__result_Mtransform_R;
	struct Ftuple_Lvector3_Mrotation_Mfloat_R;
	struct Ftuple_Lvector3_Mrotation_R;
	struct Ftuple_Lvector3_Mvector3_R;
}

namespace race_manager_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace save_point_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseAbilities_0
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseAssets_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lsupertype_Lany_R_M_Kchar_R;
	class UAssets;
	struct Ftuple_L_R;
}

namespace VerseFramework_test_device
{
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_R;
	struct Ftuple_L_R;
}

namespace NexusFramework_nexus_test_device
{
	struct Ftuple_L_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_M_Kchar_M_Kchar_R;
	struct Ftuple_L_Kchar_Mtest__result_M_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_M_Kchar_M_Kchar_M_Kchar_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_Kchar_Mlogic_M_Kchar_R;
	struct Ftuple_L_R;
}

namespace VerseFortniteInternal_0
{
	struct Ftuple_Lvk__component_Mtype_Lvk__component_M_20vk__component_R_R;
	struct Ftuple_Lplayer_Mfort__item__definition_Mint_Mlogic_R;
	struct Ftuple_Lplayer_MPlayerAttribute_MPlayerAttributeOperation_Mfloat_R;
	struct Ftuple_Lint_Mint_R;
	struct Ftuple_Lplayer_Mlogic_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lplayer__component_Mplayer__start__component_R;
	struct Ftuple_Lplayer_Mlogic_Mlogic_Mlogic_R;
	struct Ftuple_Lplayer_Mplayer__team_R;
	struct Ftuple_Lplayer_Mplayer_R;
	struct Ftuple_Lplayer_MPlayerAttribute_R;
}

namespace map_indicator_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace skydome_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace sentry_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseFortniteUI
{
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	class UUI;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace wilds_plant_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace nitro_hoop_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace map_controller_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace nitro_barrel_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace firefly_spawner_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace trick_tile_device
{
	struct Ftuple_Ltransform_Mfloat_R;
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lvector3_Mrotation_Mfloat_R;
	struct Ftuple_Lvector3_Mrotation_R;
}

namespace ai_patrol_path_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace physics_boulder_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace barrier_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace pinball_bumper_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace matchmaking_portal_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace analytics_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace shared_saved_data_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace item_spawner_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace input_trigger_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace trigger_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace character_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace gameplay_camera_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace fishing_zone_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace vehicle_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace end_game_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace npc_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace race_checkpoint_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace pulse_trigger_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace vehicle_spawner_baller_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseBasicGameplay
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lvector3_M_Kchar_R;
}

namespace crowd_volume_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace objective_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace prop_spawner_base_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace popup_dialog_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace ItemizationCoreUI_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lsupertype_Lany_R_M_Kchar_R;
	class U_Root;
	struct Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R;
	struct Ftuple_L_R;
}

namespace beacon_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace FNE_ConversationRuntime_0
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
}

namespace radio_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace EpicGamesEngine_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace vending_machine_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace grind_rail_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace team_settings_and_inventory_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseSimulationMetadata_0
{
	class USimulation;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
}

namespace ExecutionTestSuite_0
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseFortniteGameScript_fort_model
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace powerup_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace water_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VersePrototypeGameplay_NodePriorityQueue
{
	struct Ftuple_Lnav__grid__node__2d_M_Knav__grid__node__2d_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Knav__grid__node__2d_Mnav__grid__node__2d_R;
}

namespace dance_mannequin_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VersePrototypeGameplay_simple_gameplay_script_component
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace elimination_feed_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace pinball_flipper_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace shooting_range_target_track_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace BridgeComponent
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace campfire_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace audio_player_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace EpicGamesAssets_0
{
	class UAssets;
	struct Ftuple_L_R;
}

namespace video_player_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace accolades_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseUI_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lwidget_Mplayer__ui__slot_R;
	class UUI;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
	struct Ftuple_Lsupertype_Lany_R_M_Kchar_R;
}

namespace advanced_storm_beacon_device
{
	struct Ftuple_Ltransform_Mfloat_R;
	struct Ftuple_Lvector3_Mrotation_Mfloat_R;
	struct Ftuple_Lvector3_Mrotation_R;
}

namespace EntityInteract_0
{
	struct Ftuple_Lagent_Mfloat_R;
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_Kchar_M_Kchar_M_5b_Kchar_5dlocalizable__value_R;
}

namespace Neck_CtrlRig
{
	class URigVMMemory_Literal;
	class URigVMMemory_Work;
}

namespace signal_remote_manager_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseCamera
{
	struct Ftuple_Laccessor_Mfloat_R;
	struct Ftuple_L_R;
}

namespace animated_mesh_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace trigger_base_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseNative_0
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace item_granter_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lagent_Mint_R;
}

namespace teleporter_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace physics_tree_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace Execution
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace patchwork_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace timed_objective_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace ball_spawner_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VerseFramework_test_suite
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace player_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace player_checkpoint_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VersePrototypeGameplay_build_path_astar_args
{
	struct Ftuple_Lvector2i_Mvector2i_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace effect_volume_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace audio_mixer_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace base_item_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseFramework_device_event_agent_handler_mock
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseExperimental
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_Lint_Mint_R;
}

namespace player_counter_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace EntityTestSuite
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace VersePrototypeGameplay_simple_grid_occupancy
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseFramework_test_case
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace ItemizationCoreRuntime_0
{
	class U_SolarisSignatureFunctionOuter;
	class U_Root;
	struct Ftuple_L_R;
}

namespace color_changing_tiles_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace capture_item_spawner_device
{
	struct Ftuple_L_R;
	class U_SolarisSignatureFunctionOuter;
}

namespace movement_modulator_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseSimulation_0
{
	class USimulation;
	struct Ftuple_L_R;
}

namespace VerseFortniteGameScript_fort_scene_object
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace VerseFramework_device_event_void_handler_mock
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace healing_cactus_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace cinematic_sequence_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace round_settings_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace creature_manager_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace down_but_not_out_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace camera_focus_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace hud_controller_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace real_time_clock_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace streaming_radio_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace vfx_creator_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace clapboard_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace fire_volume_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace skydive_volume_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace guard_spawner_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace character_device_controller_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace air_vent_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace button_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace conditional_button_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
	struct Ftuple_Lagent_Mint_R;
	struct Ftuple_Lint_Mint_R;
}

namespace shooting_range_target_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace timer_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}

namespace chair_device
{
	class U_SolarisSignatureFunctionOuter;
	struct Ftuple_L_R;
}
