#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: air_vent_device

#include "Basic.hpp"

#include "VerseDevices_classes.hpp"
#include "CoreUObject_classes.hpp"
#include "VerseNative_structs.hpp"


namespace SDK
{

// VerseClass air_vent_device.$SolarisSignatureFunctionOuter
// 0x0000 (0x0030 - 0x0030)
class air_vent_device::U_SolarisSignatureFunctionOuter final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"VerseClass air_vent_device.$SolarisSignatureFunctionOuter", true>();
	}
	static class air_vent_device::U_SolarisSignatureFunctionOuter* GetDefaultObj()
	{
		return GetDefaultObjImpl<air_vent_device::U_SolarisSignatureFunctionOuter>();
	}
};

// VerseClass air_vent_device.air_vent_device
// 0x0020 (0x00E0 - 0x00C0)
class Uair_vent_device final : public UDevices_creative_device_base
{
public:
	class UDevices_device_function*               __verse_0x5BDC7A5C_EnableFunction;                 // 0x00C0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDevices_device_function*               __verse_0xC9184E23_DisableFunction;                // 0x00C8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDevices_device_function*               __verse_0x5BB90C4F_ActivateFunction;               // 0x00D0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void _Block();
	void _InitCDO();
	void _InitInstance();
	void _L_2fFortnite_2ecom_2fDevices_2fair__vent__device_N_RActivate(const struct air_vent_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument);
	void _L_2fFortnite_2ecom_2fDevices_2fair__vent__device_N_RDisable(const struct air_vent_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument);
	void _L_2fFortnite_2ecom_2fDevices_2fair__vent__device_N_REnable(const struct air_vent_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"air_vent_device">();
	}
	static class Uair_vent_device* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uair_vent_device>();
	}
};

}

