#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AssetDefinition

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class AssetDefinition.AssetDefinition
// 0x0018 (0x0048 - 0x0030)
class UAssetDefinition : public UObject
{
public:
	uint8                                         Pad_30[0x18];                                      // 0x0030(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AssetDefinition">();
	}
	static class UAssetDefinition* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAssetDefinition>();
	}
};

// Class AssetDefinition.AssetDefinitionRegistry
// 0x0090 (0x00C0 - 0x0030)
class UAssetDefinitionRegistry final : public UObject
{
public:
	TMap<TSoftClassPtr<class UClass>, class UAssetDefinition*> AssetDefinitions;                                  // 0x0030(0x0050)(UObjectWrapper, NativeAccessSpecifierPrivate)
	uint8                                         Pad_80[0x40];                                      // 0x0080(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AssetDefinitionRegistry">();
	}
	static class UAssetDefinitionRegistry* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAssetDefinitionRegistry>();
	}
};

}

