#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: base_item_spawner_device

#include "Basic.hpp"

#include "base_item_spawner_device_classes.hpp"
#include "base_item_spawner_device_parameters.hpp"


namespace SDK
{

// Function base_item_spawner_device.base_item_spawner_device.$Block
// ()

void Ubase_item_spawner_device::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("base_item_spawner_device", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function base_item_spawner_device.base_item_spawner_device.$InitCDO
// (HasDefaults)

void Ubase_item_spawner_device::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("base_item_spawner_device", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function base_item_spawner_device.base_item_spawner_device.$InitInstance
// ()

void Ubase_item_spawner_device::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("base_item_spawner_device", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function base_item_spawner_device.base_item_spawner_device._L_2fFortnite_2ecom_2fDevices_2fbase__item__spawner__device_N_RDisable
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct base_item_spawner_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ubase_item_spawner_device::_L_2fFortnite_2ecom_2fDevices_2fbase__item__spawner__device_N_RDisable(const struct base_item_spawner_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("base_item_spawner_device", "_L_2fFortnite_2ecom_2fDevices_2fbase__item__spawner__device_N_RDisable");

	Params::base_item_spawner_device__L_2fFortnite_2ecom_2fDevices_2fbase__item__spawner__device_N_RDisable Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function base_item_spawner_device.base_item_spawner_device._L_2fFortnite_2ecom_2fDevices_2fbase__item__spawner__device_N_REnable
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct base_item_spawner_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ubase_item_spawner_device::_L_2fFortnite_2ecom_2fDevices_2fbase__item__spawner__device_N_REnable(const struct base_item_spawner_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("base_item_spawner_device", "_L_2fFortnite_2ecom_2fDevices_2fbase__item__spawner__device_N_REnable");

	Params::base_item_spawner_device__L_2fFortnite_2ecom_2fDevices_2fbase__item__spawner__device_N_REnable Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}

}

