#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: capture_area_device

#include "Basic.hpp"

#include "capture_area_device_classes.hpp"
#include "capture_area_device_parameters.hpp"


namespace SDK
{

// Function capture_area_device.capture_area_device.$Block
// ()

void Ucapture_area_device::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function capture_area_device.capture_area_device.$InitCDO
// (HasDefaults)

void Ucapture_area_device::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function capture_area_device.capture_area_device.$InitInstance
// ()

void Ucapture_area_device::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RActivateObjectivePulse
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RActivateObjectivePulse(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RActivateObjectivePulse");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RActivateObjectivePulse Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RAllowCapture
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RAllowCapture(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RAllowCapture");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RAllowCapture Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDeactivateObjectivePulse
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDeactivateObjectivePulse(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDeactivateObjectivePulse");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDeactivateObjectivePulse Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDisable
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDisable(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDisable");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDisable Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDisallowCapture
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDisallowCapture(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDisallowCapture");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RDisallowCapture Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_REnable
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_REnable(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_REnable");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_REnable Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGetHeight
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGetHeight(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGetHeight");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGetHeight Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGetRadius
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGetRadius(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGetRadius");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGetRadius Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGiveControl_L_Nagent_R
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// class USimulation_agent*                __verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGiveControl_L_Nagent_R(class USimulation_agent* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGiveControl_L_Nagent_R");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RGiveControl_L_Nagent_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RNeutralize
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RNeutralize(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RNeutralize");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RNeutralize Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RReset
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RReset(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RReset");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RReset Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RSetHeight_L_Nfloat_R
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// double                                  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RSetHeight_L_Nfloat_R(double __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RSetHeight_L_Nfloat_R");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RSetHeight_L_Nfloat_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RSetRadius_L_Nfloat_R
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// double                                  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RSetRadius_L_Nfloat_R(double __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RSetRadius_L_Nfloat_R");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RSetRadius_L_Nfloat_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RToggleCaptureAllowed
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RToggleCaptureAllowed(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RToggleCaptureAllowed");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RToggleCaptureAllowed Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function capture_area_device.capture_area_device._L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RToggleEnabled
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct capture_area_device::Ftuple_L_R  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucapture_area_device::_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RToggleEnabled(const struct capture_area_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("capture_area_device", "_L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RToggleEnabled");

	Params::capture_area_device__L_2fFortnite_2ecom_2fDevices_2fcapture__area__device_N_RToggleEnabled Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}

}

