#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ContentResolver

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class ContentResolver.PluginBatchLoaderHelper
// 0x0080 (0x00B0 - 0x0030)
class UPluginBatchLoaderHelper final : public UObject
{
public:
	uint8                                         Pad_30[0x80];                                      // 0x0030(0x0080)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PluginBatchLoaderHelper">();
	}
	static class UPluginBatchLoaderHelper* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPluginBatchLoaderHelper>();
	}
};

// Class ContentResolver.ExternalContentLoader
// 0x0018 (0x0050 - 0x0038)
class UExternalContentLoader final : public UEngineSubsystem
{
public:
	uint8                                         Pad_38[0x18];                                      // 0x0038(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ExternalContentLoader">();
	}
	static class UExternalContentLoader* GetDefaultObj()
	{
		return GetDefaultObjImpl<UExternalContentLoader>();
	}
};

}

