#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ContentBrowser

#include "Basic.hpp"


namespace SDK::Params
{

// Function ContentBrowser.ContentBrowserAssetContextMenuContext.GetSelectedObjects
// 0x0010 (0x0010 - 0x0000)
struct ContentBrowserAssetContextMenuContext_GetSelectedObjects final
{
public:
	TArray<class UObject*>                        ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function ContentBrowser.ContentBrowserAssetContextMenuContext.LoadSelectedObjects
// 0x0060 (0x0060 - 0x0000)
struct ContentBrowserAssetContextMenuContext_LoadSelectedObjects final
{
public:
	TSet<class FName>                             LoadTags;                                          // 0x0000(0x0050)(Parm, NativeAccessSpecifierPublic)
	TArray<class UObject*>                        ReturnValue;                                       // 0x0050(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function ContentBrowser.ContentBrowserAssetContextMenuContext.LoadSelectedObjectsIfNeeded
// 0x0010 (0x0010 - 0x0000)
struct ContentBrowserAssetContextMenuContext_LoadSelectedObjectsIfNeeded final
{
public:
	TArray<class UObject*>                        ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

}

