#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreatorProfileRuntime

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class CreatorProfileRuntime.CreatorProfileBlueprintFunctionLibrary
// 0x0000 (0x0030 - 0x0030)
class UCreatorProfileBlueprintFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool GetLinkData(const class AActor* ActorContext, class FString* OutCreatorName, class FString* OutSupportCode);
	static bool GetOwnerProfile(const class AActor* ActorContext, class FString* OutCreatorName, class FString* OutSupportCode);
	static bool IsMinor(const class APlayerController* PC);
	static bool IsUGCRestricted(const class APlayerController* PC);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CreatorProfileBlueprintFunctionLibrary">();
	}
	static class UCreatorProfileBlueprintFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreatorProfileBlueprintFunctionLibrary>();
	}
};

}

