#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: creature_spawner_device

#include "Basic.hpp"

#include "creature_spawner_device_classes.hpp"
#include "creature_spawner_device_parameters.hpp"


namespace SDK
{

// Function creature_spawner_device.creature_spawner_device.$Block
// ()

void Ucreature_spawner_device::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("creature_spawner_device", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function creature_spawner_device.creature_spawner_device.$InitCDO
// (HasDefaults)

void Ucreature_spawner_device::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("creature_spawner_device", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function creature_spawner_device.creature_spawner_device.$InitInstance
// ()

void Ucreature_spawner_device::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("creature_spawner_device", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function creature_spawner_device.creature_spawner_device._L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RDestroySpawner
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct creature_spawner_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucreature_spawner_device::_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RDestroySpawner(const struct creature_spawner_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("creature_spawner_device", "_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RDestroySpawner");

	Params::creature_spawner_device__L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RDestroySpawner Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function creature_spawner_device.creature_spawner_device._L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RDisable
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct creature_spawner_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucreature_spawner_device::_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RDisable(const struct creature_spawner_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("creature_spawner_device", "_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RDisable");

	Params::creature_spawner_device__L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RDisable Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function creature_spawner_device.creature_spawner_device._L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_REliminateCreatures
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct creature_spawner_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucreature_spawner_device::_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_REliminateCreatures(const struct creature_spawner_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("creature_spawner_device", "_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_REliminateCreatures");

	Params::creature_spawner_device__L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_REliminateCreatures Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function creature_spawner_device.creature_spawner_device._L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_REnable
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct creature_spawner_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucreature_spawner_device::_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_REnable(const struct creature_spawner_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("creature_spawner_device", "_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_REnable");

	Params::creature_spawner_device__L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_REnable Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function creature_spawner_device.creature_spawner_device._L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RGetSpawnLimit
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct creature_spawner_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int64 Ucreature_spawner_device::_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RGetSpawnLimit(const struct creature_spawner_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("creature_spawner_device", "_L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RGetSpawnLimit");

	Params::creature_spawner_device__L_2fFortnite_2ecom_2fDevices_2fcreature__spawner__device_N_RGetSpawnLimit Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

