#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EditTimeWindowModal

#include "Basic.hpp"

#include "EditTimeWindowModal_classes.hpp"
#include "EditTimeWindowModal_parameters.hpp"


namespace SDK
{

// Function EditTimeWindowModal.EditTimeWindowModal_C.BndEvt__AthenaSpectateMatchModal_WBP_UIKit_Button_Quiet_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UEditTimeWindowModal_C::BndEvt__AthenaSpectateMatchModal_WBP_UIKit_Button_Quiet_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "BndEvt__AthenaSpectateMatchModal_WBP_UIKit_Button_Quiet_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature");

	Params::EditTimeWindowModal_C_BndEvt__AthenaSpectateMatchModal_WBP_UIKit_Button_Quiet_K2Node_ComponentBoundEvent_11_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.BndEvt__EditTimeWindowModal_AcceptButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UEditTimeWindowModal_C::BndEvt__EditTimeWindowModal_AcceptButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "BndEvt__EditTimeWindowModal_AcceptButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::EditTimeWindowModal_C_BndEvt__EditTimeWindowModal_AcceptButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.BndEvt__EditTimeWindowModal_Button_CloseTouch_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UEditTimeWindowModal_C::BndEvt__EditTimeWindowModal_Button_CloseTouch_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "BndEvt__EditTimeWindowModal_Button_CloseTouch_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::EditTimeWindowModal_C_BndEvt__EditTimeWindowModal_Button_CloseTouch_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.BndEvt__EditTimeWindowModal_EndTimeSelector_K2Node_ComponentBoundEvent_8_OnTimeChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// struct FDailyTime                       NewTime                                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UEditTimeWindowModal_C::BndEvt__EditTimeWindowModal_EndTimeSelector_K2Node_ComponentBoundEvent_8_OnTimeChanged__DelegateSignature(const struct FDailyTime& NewTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "BndEvt__EditTimeWindowModal_EndTimeSelector_K2Node_ComponentBoundEvent_8_OnTimeChanged__DelegateSignature");

	Params::EditTimeWindowModal_C_BndEvt__EditTimeWindowModal_EndTimeSelector_K2Node_ComponentBoundEvent_8_OnTimeChanged__DelegateSignature Parms{};

	Parms.NewTime = std::move(NewTime);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.BndEvt__EditTimeWindowModal_RemoveButton_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UEditTimeWindowModal_C::BndEvt__EditTimeWindowModal_RemoveButton_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "BndEvt__EditTimeWindowModal_RemoveButton_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature");

	Params::EditTimeWindowModal_C_BndEvt__EditTimeWindowModal_RemoveButton_K2Node_ComponentBoundEvent_6_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.BndEvt__EditTimeWindowModal_StartTimeSelector_K2Node_ComponentBoundEvent_7_OnTimeChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// struct FDailyTime                       NewTime                                                (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UEditTimeWindowModal_C::BndEvt__EditTimeWindowModal_StartTimeSelector_K2Node_ComponentBoundEvent_7_OnTimeChanged__DelegateSignature(const struct FDailyTime& NewTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "BndEvt__EditTimeWindowModal_StartTimeSelector_K2Node_ComponentBoundEvent_7_OnTimeChanged__DelegateSignature");

	Params::EditTimeWindowModal_C_BndEvt__EditTimeWindowModal_StartTimeSelector_K2Node_ComponentBoundEvent_7_OnTimeChanged__DelegateSignature Parms{};

	Parms.NewTime = std::move(NewTime);

	UObject::ProcessEvent(Func, &Parms);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.ExecuteUbergraph_EditTimeWindowModal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEditTimeWindowModal_C::ExecuteUbergraph_EditTimeWindowModal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "ExecuteUbergraph_EditTimeWindowModal");

	Params::EditTimeWindowModal_C_ExecuteUbergraph_EditTimeWindowModal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.OnEndTimeSelectorNavigated
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UEditTimeWindowModal_C::OnEndTimeSelectorNavigated(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "OnEndTimeSelectorNavigated");

	Params::EditTimeWindowModal_C_OnEndTimeSelectorNavigated Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.OnInitializeTimeWindow
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FDailyTimeWindow                 TimeWindow                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// bool                                    bIsNewWindow                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UEditTimeWindowModal_C::OnInitializeTimeWindow(const struct FDailyTimeWindow& TimeWindow, const bool bIsNewWindow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "OnInitializeTimeWindow");

	Params::EditTimeWindowModal_C_OnInitializeTimeWindow Parms{};

	Parms.TimeWindow = std::move(TimeWindow);
	Parms.bIsNewWindow = bIsNewWindow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.OnStartTimeSelectorNavigated
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UEditTimeWindowModal_C::OnStartTimeSelectorNavigated(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "OnStartTimeSelectorNavigated");

	Params::EditTimeWindowModal_C_OnStartTimeSelectorNavigated Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.RefreshUI
// (BlueprintCallable, BlueprintEvent)

void UEditTimeWindowModal_C::RefreshUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "RefreshUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EditTimeWindowModal.EditTimeWindowModal_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UEditTimeWindowModal_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EditTimeWindowModal_C", "BP_GetDesiredFocusTarget");

	Params::EditTimeWindowModal_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

