#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EntityInteract

#include "Basic.hpp"

#include "EntityInteract_classes.hpp"
#include "EntityInteract_parameters.hpp"


namespace SDK
{

// Function EntityInteract.EntityInteractLibrary.EntityInteractGetActor
// (Final, Native, Static, Public, HasOutParams)
// Parameters:
// class UObject*                          WorldContextObject                                     (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FHitResult                       HitResult                                              (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AActor* UEntityInteractLibrary::EntityInteractGetActor(const class UObject* WorldContextObject, const struct FHitResult& HitResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("EntityInteractLibrary", "EntityInteractGetActor");

	Params::EntityInteractLibrary_EntityInteractGetActor Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.HitResult = std::move(HitResult);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function EntityInteract.EntityInteractProxyActor.NetMultiCastBeginCooldownTimer
// (Final, Net, NetReliable, Native, Event, NetMulticast, Private)
// Parameters:
// float                                   CoolDownTime                                           (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AEntityInteractProxyActor::NetMultiCastBeginCooldownTimer(const float CoolDownTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EntityInteractProxyActor", "NetMultiCastBeginCooldownTimer");

	Params::EntityInteractProxyActor_NetMultiCastBeginCooldownTimer Parms{};

	Parms.CoolDownTime = CoolDownTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function EntityInteract.EntityInteractProxyActor.OnRep_CannotInteractMessage
// (Final, Native, Private)

void AEntityInteractProxyActor::OnRep_CannotInteractMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EntityInteractProxyActor", "OnRep_CannotInteractMessage");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function EntityInteract.EntityInteractProxyActor.OnRep_CoolDownMessage
// (Final, Native, Private)

void AEntityInteractProxyActor::OnRep_CoolDownMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EntityInteractProxyActor", "OnRep_CoolDownMessage");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function EntityInteract.EntityInteractProxyActor.OnRep_InteractMessage
// (Final, Native, Private)

void AEntityInteractProxyActor::OnRep_InteractMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EntityInteractProxyActor", "OnRep_InteractMessage");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

