#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortniteDeveloperTools

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class FortniteDeveloperTools.CreativeAssetCostDirectoryCommandlet
// 0x0000 (0x0088 - 0x0088)
class UCreativeAssetCostDirectoryCommandlet final : public UCommandlet
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CreativeAssetCostDirectoryCommandlet">();
	}
	static class UCreativeAssetCostDirectoryCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeAssetCostDirectoryCommandlet>();
	}
};

}

