#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortContentMetaDataWriter

#include "Basic.hpp"

#include "EditorSubsystem_classes.hpp"


namespace SDK
{

// Class FortContentMetaDataWriter.FortContentMetaDataWriterSubsystem
// 0x0008 (0x0040 - 0x0038)
class UFortContentMetaDataWriterSubsystem final : public UEditorSubsystem
{
public:
	uint8                                         Pad_38[0x8];                                       // 0x0038(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"FortContentMetaDataWriterSubsystem">();
	}
	static class UFortContentMetaDataWriterSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortContentMetaDataWriterSubsystem>();
	}
};

}

