#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortOcclusionNetRelevancy

#include "Basic.hpp"

#include "FortOcclusionNetRelevancy_classes.hpp"
#include "FortOcclusionNetRelevancy_parameters.hpp"


namespace SDK
{

// Function FortOcclusionNetRelevancy.FortOcclusionClientStatsComponent.OnRep_IsSystemEnabled
// (Final, Native, Private)

void UFortOcclusionClientStatsComponent::OnRep_IsSystemEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortOcclusionClientStatsComponent", "OnRep_IsSystemEnabled");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function FortOcclusionNetRelevancy.FortOcclusionClientStatsComponent.OnRep_IsUsingOcclusionFilter
// (Final, Native, Private)

void UFortOcclusionClientStatsComponent::OnRep_IsUsingOcclusionFilter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortOcclusionClientStatsComponent", "OnRep_IsUsingOcclusionFilter");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function FortOcclusionNetRelevancy.FortOcclusionNetRelevancyWorldSubsystem.FilterActorForAllConections
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)
// Parameters:
// class AActor*                           Actor                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bOccluded                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFortOcclusionNetRelevancyWorldSubsystem::FilterActorForAllConections(class AActor* Actor, bool bOccluded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortOcclusionNetRelevancyWorldSubsystem", "FilterActorForAllConections");

	Params::FortOcclusionNetRelevancyWorldSubsystem_FilterActorForAllConections Parms{};

	Parms.Actor = Actor;
	Parms.bOccluded = bOccluded;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function FortOcclusionNetRelevancy.FortOcclusionNetRelevancyWorldSubsystem.OnPawnEndPlay
// (Final, Native, Protected)
// Parameters:
// class AActor*                           Actor                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EEndPlayReason                          EndPlayReason                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFortOcclusionNetRelevancyWorldSubsystem::OnPawnEndPlay(class AActor* Actor, EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortOcclusionNetRelevancyWorldSubsystem", "OnPawnEndPlay");

	Params::FortOcclusionNetRelevancyWorldSubsystem_OnPawnEndPlay Parms{};

	Parms.Actor = Actor;
	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function FortOcclusionNetRelevancy.FortOcclusionNetRelevancyWorldSubsystem.SetActorOccludedToConnections
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)
// Parameters:
// class AActor*                           Actor                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<int32>                           ConnectionIds                                          (Parm, ZeroConstructor, NativeAccessSpecifierPublic)
// bool                                    bOccluded                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFortOcclusionNetRelevancyWorldSubsystem::SetActorOccludedToConnections(class AActor* Actor, const TArray<int32>& ConnectionIds, bool bOccluded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortOcclusionNetRelevancyWorldSubsystem", "SetActorOccludedToConnections");

	Params::FortOcclusionNetRelevancyWorldSubsystem_SetActorOccludedToConnections Parms{};

	Parms.Actor = Actor;
	Parms.ConnectionIds = std::move(ConnectionIds);
	Parms.bOccluded = bOccluded;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

