#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameFeatureSet

#include "Basic.hpp"

#include "GameFeatureSet_classes.hpp"
#include "GameFeatureSet_parameters.hpp"


namespace SDK
{

// Function GameFeatureSet.GameFeatureSetSubsystem.GetDiscoveredFeatureSetOptions
// (Final, Native, Static, Public, EditorOnly)
// Parameters:
// TArray<class FString>                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class FString> UGameFeatureSetSubsystem::GetDiscoveredFeatureSetOptions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("GameFeatureSetSubsystem", "GetDiscoveredFeatureSetOptions");

	Params::GameFeatureSetSubsystem_GetDiscoveredFeatureSetOptions Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

