#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: health_powerup_device

#include "Basic.hpp"

#include "health_powerup_device_classes.hpp"
#include "health_powerup_device_parameters.hpp"


namespace SDK
{

// Function health_powerup_device.health_powerup_device.$Block
// ()

void Uhealth_powerup_device::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("health_powerup_device", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function health_powerup_device.health_powerup_device.$InitCDO
// (HasDefaults)

void Uhealth_powerup_device::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("health_powerup_device", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function health_powerup_device.health_powerup_device.$InitInstance
// ()

void Uhealth_powerup_device::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("health_powerup_device", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function health_powerup_device.health_powerup_device._L_2fFortnite_2ecom_2fDevices_2fhealth__powerup__device_N_RGetMagnitude
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct health_powerup_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double Uhealth_powerup_device::_L_2fFortnite_2ecom_2fDevices_2fhealth__powerup__device_N_RGetMagnitude(const struct health_powerup_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("health_powerup_device", "_L_2fFortnite_2ecom_2fDevices_2fhealth__powerup__device_N_RGetMagnitude");

	Params::health_powerup_device__L_2fFortnite_2ecom_2fDevices_2fhealth__powerup__device_N_RGetMagnitude Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function health_powerup_device.health_powerup_device._L_2fFortnite_2ecom_2fDevices_2fhealth__powerup__device_N_RSetMagnitude_L_Nfloat_R
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// double                                  __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhealth_powerup_device::_L_2fFortnite_2ecom_2fDevices_2fhealth__powerup__device_N_RSetMagnitude_L_Nfloat_R(double __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("health_powerup_device", "_L_2fFortnite_2ecom_2fDevices_2fhealth__powerup__device_N_RSetMagnitude_L_Nfloat_R");

	Params::health_powerup_device__L_2fFortnite_2ecom_2fDevices_2fhealth__powerup__device_N_RSetMagnitude_L_Nfloat_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}

}

