#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JunoFishing

#include "Basic.hpp"

#include "ModularGameplay_classes.hpp"
#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"
#include "JunoFishing_structs.hpp"


namespace SDK
{

// Class JunoFishing.JunoFishingAnalytics
// 0x0000 (0x0030 - 0x0030)
class UJunoFishingAnalytics final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JunoFishingAnalytics">();
	}
	static class UJunoFishingAnalytics* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJunoFishingAnalytics>();
	}
};

// Class JunoFishing.JunoFishingBlueprintLibrary
// 0x0000 (0x0030 - 0x0030)
class UJunoFishingBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void FireEvent_BeginJunoFishingSession(class AFortPlayerPawn* PlayerPawn);
	static void FireEvent_EndJunoFishingSession(class AFortPlayerPawn* PlayerPawn, const class UFortWorldItemDefinition* ItemFished, const bool bFromHotspot, const bool bIsPlayerSpawnedHotspot, const class FString& HotspotTierTag, const class FString& WaterBodyName, const class FString& CatchTypeName, const class AActor* ItemUsedToFish);
	static struct FGameplayTagContainer GetFishingTags(class AFortPlayerPawn* PlayerPawn);
	static struct FGameplayTag RollFishingBobType(const struct FGameplayTagContainer& FishingTags);
	static struct FJunoFishingCatchWeights RollFishingCatch(const class UObject* WorldContextObject, const struct FGameplayTagContainer& FishingTags, const struct FGameplayTag& BobType);
	static TArray<struct FFortItemEntry> RollFishingCatchItems(const class UObject* WorldContextObject, const struct FGameplayTagContainer& FishingTags, const struct FGameplayTag& BobType);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JunoFishingBlueprintLibrary">();
	}
	static class UJunoFishingBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJunoFishingBlueprintLibrary>();
	}
};

// Class JunoFishing.JunoPlayerControllerComponent_FishingAnalytics
// 0x0050 (0x0128 - 0x00D8)
class UJunoPlayerControllerComponent_FishingAnalytics final : public UControllerComponent
{
public:
	struct FJunoPlayerFishingTelemetryData        PlayerFishingTelemetryData;                        // 0x00D8(0x0050)(Transient, Protected, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JunoPlayerControllerComponent_FishingAnalytics">();
	}
	static class UJunoPlayerControllerComponent_FishingAnalytics* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJunoPlayerControllerComponent_FishingAnalytics>();
	}
};

}

