#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MetaHumanFaceFittingSolverEditor

#include "Basic.hpp"

#include "UnrealEd_classes.hpp"


namespace SDK
{

// Class MetaHumanFaceFittingSolverEditor.AssetDefinition_MetaHumanFaceFittingSolver
// 0x0000 (0x0048 - 0x0048)
class UAssetDefinition_MetaHumanFaceFittingSolver final : public UAssetDefinitionDefault
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AssetDefinition_MetaHumanFaceFittingSolver">();
	}
	static class UAssetDefinition_MetaHumanFaceFittingSolver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAssetDefinition_MetaHumanFaceFittingSolver>();
	}
};

// Class MetaHumanFaceFittingSolverEditor.MetaHumanFaceFittingSolverFactoryNew
// 0x0000 (0x0088 - 0x0088)
class UMetaHumanFaceFittingSolverFactoryNew final : public UFactory
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MetaHumanFaceFittingSolverFactoryNew">();
	}
	static class UMetaHumanFaceFittingSolverFactoryNew* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMetaHumanFaceFittingSolverFactoryNew>();
	}
};

}

