#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: music_manager_device

#include "Basic.hpp"

#include "music_manager_device_classes.hpp"


namespace SDK
{

// Function music_manager_device.music_manager_device.$Block
// ()

void Umusic_manager_device::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("music_manager_device", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function music_manager_device.music_manager_device.$InitCDO
// ()

void Umusic_manager_device::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("music_manager_device", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function music_manager_device.music_manager_device.$InitInstance
// ()

void Umusic_manager_device::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("music_manager_device", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}

}

