#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MusterConsumablesUI

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// Class MusterConsumablesUI.EnergyDrinkStaminaBarOverlayWidget
// 0x0010 (0x0498 - 0x0488)
class UEnergyDrinkStaminaBarOverlayWidget final : public UFortHUDElementWidget
{
public:
	uint8                                         Pad_488[0x10];                                     // 0x0488(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnPlayerDeadStateChanged(class AFortPlayerStateAthena* PlayerState, bool bIsDead);
	void OnPlayerStateSet(class AFortPlayerStateAthena* InPlayerState);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"EnergyDrinkStaminaBarOverlayWidget">();
	}
	static class UEnergyDrinkStaminaBarOverlayWidget* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEnergyDrinkStaminaBarOverlayWidget>();
	}
};

}

