#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NiagaraEditor

#include "Basic.hpp"

#include "NiagaraEditor_classes.hpp"
#include "NiagaraEditor_parameters.hpp"


namespace SDK
{

// Function NiagaraEditor.NiagaraPythonModule.GetObject
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UNiagaraStackModuleItem*          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraStackModuleItem* UNiagaraPythonModule::GetObject() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonModule", "GetObject");

	Params::NiagaraPythonModule_GetObject Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateBoolLocalValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    InBoolValue                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateBoolLocalValueInput(class UObject* InOuter, class FName InInputName, bool bInHasEditCondition, bool bInEditConditionValue, bool InBoolValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateBoolLocalValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateBoolLocalValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InBoolValue = InBoolValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateDataValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraDataInterface*            InDataValue                                            (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateDataValueInput(class UObject* InOuter, class FName InInputName, bool bInHasEditCondition, bool bInEditConditionValue, class UNiagaraDataInterface* InDataValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateDataValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateDataValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InDataValue = InDataValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateDynamicValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputTypeName                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           InDynamicValueName                                     (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraScript*                   InDynamicValue                                         (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateDynamicValueInput(class UObject* InOuter, class FName InInputName, class FName InInputTypeName, bool bInHasEditCondition, bool bInEditConditionValue, const class FString& InDynamicValueName, class UNiagaraScript* InDynamicValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateDynamicValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateDynamicValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.InInputTypeName = InInputTypeName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InDynamicValueName = std::move(InDynamicValueName);
	Parms.InDynamicValue = InDynamicValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateEnumLocalValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditCoditionValue                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUserDefinedEnum*                 InEnumType                                             (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   InEnumValue                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateEnumLocalValueInput(class UObject* InOuter, class FName InInputName, bool bInHasEditCondition, bool bInEditCoditionValue, class UUserDefinedEnum* InEnumType, int32 InEnumValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateEnumLocalValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateEnumLocalValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditCoditionValue = bInEditCoditionValue;
	Parms.InEnumType = InEnumType;
	Parms.InEnumValue = InEnumValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateExpressionValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputTypeName                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           InExpressionValue                                      (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateExpressionValueInput(class UObject* InOuter, class FName InInputName, class FName InInputTypeName, bool bInHasEditCondition, bool bInEditConditionValue, const class FString& InExpressionValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateExpressionValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateExpressionValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.InInputTypeName = InInputTypeName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InExpressionValue = std::move(InExpressionValue);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateFloatLocalValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   InLocalValue                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateFloatLocalValueInput(class UObject* InOuter, class FName InInputName, bool bInHasEditCondition, bool bInEditConditionValue, float InLocalValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateFloatLocalValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateFloatLocalValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InLocalValue = InLocalValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateIntLocalValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   InLocalValue                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateIntLocalValueInput(class UObject* InOuter, class FName InInputName, bool bInHasEditCondition, bool bInEditConditionValue, int32 InLocalValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateIntLocalValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateIntLocalValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InLocalValue = InLocalValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateLinkedValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputTypeName                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InLinkedValue                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateLinkedValueInput(class UObject* InOuter, class FName InInputName, class FName InInputTypeName, bool bInHasEditCondition, bool bInEditConditionValue, class FName InLinkedValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateLinkedValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateLinkedValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.InInputTypeName = InInputTypeName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InLinkedValue = InLinkedValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateStructLocalValueInput
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUserDefinedStruct*               InStructValue                                          (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateStructLocalValueInput(class UObject* InOuter, class FName InInputName, bool bInHasEditCondition, bool bInEditConditionValue, class UUserDefinedStruct* InStructValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateStructLocalValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateStructLocalValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InStructValue = InStructValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateVec2LocalValueInput
// (Final, RequiredAPI, Native, Static, Public, HasDefaults, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector2D                        InVec2Value                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateVec2LocalValueInput(class UObject* InOuter, class FName InInputName, bool bInHasEditCondition, bool bInEditConditionValue, const struct FVector2D& InVec2Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateVec2LocalValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateVec2LocalValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InVec2Value = std::move(InVec2Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.CreateVec3LocalValueInput
// (Final, RequiredAPI, Native, Static, Public, HasDefaults, BlueprintCallable, BlueprintPure)
// Parameters:
// class UObject*                          InOuter                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInHasEditCondition                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInEditConditionValue                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          InVec3Value                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraClipboardFunctionInput* UNiagaraClipboardEditorScriptingUtilities::CreateVec3LocalValueInput(class UObject* InOuter, class FName InInputName, bool bInHasEditCondition, bool bInEditConditionValue, const struct FVector& InVec3Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "CreateVec3LocalValueInput");

	Params::NiagaraClipboardEditorScriptingUtilities_CreateVec3LocalValueInput Parms{};

	Parms.InOuter = InOuter;
	Parms.InInputName = InInputName;
	Parms.bInHasEditCondition = bInHasEditCondition;
	Parms.bInEditConditionValue = bInEditConditionValue;
	Parms.InVec3Value = std::move(InVec3Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.GetTypeName
// (Final, RequiredAPI, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UNiagaraClipboardFunctionInput*   InInput                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FName                             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FName UNiagaraClipboardEditorScriptingUtilities::GetTypeName(const class UNiagaraClipboardFunctionInput* InInput)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "GetTypeName");

	Params::NiagaraClipboardEditorScriptingUtilities_GetTypeName Parms{};

	Parms.InInput = InInput;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.TryGetInputByName
// (Final, RequiredAPI, Native, Static, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// TArray<class UNiagaraClipboardFunctionInput*>InInputs                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// class FName                             InInputName                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bOutSucceeded                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraClipboardFunctionInput*   OutInput                                               (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UNiagaraClipboardEditorScriptingUtilities::TryGetInputByName(const TArray<class UNiagaraClipboardFunctionInput*>& InInputs, class FName InInputName, bool* bOutSucceeded, class UNiagaraClipboardFunctionInput** OutInput)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "TryGetInputByName");

	Params::NiagaraClipboardEditorScriptingUtilities_TryGetInputByName Parms{};

	Parms.InInputs = std::move(InInputs);
	Parms.InInputName = InInputName;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bOutSucceeded != nullptr)
		*bOutSucceeded = Parms.bOutSucceeded;

	if (OutInput != nullptr)
		*OutInput = Parms.OutInput;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.TryGetLocalValueAsFloat
// (Final, RequiredAPI, Native, Static, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// class UNiagaraClipboardFunctionInput*   InInput                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bOutSucceeded                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   OutValue                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UNiagaraClipboardEditorScriptingUtilities::TryGetLocalValueAsFloat(const class UNiagaraClipboardFunctionInput* InInput, bool* bOutSucceeded, float* OutValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "TryGetLocalValueAsFloat");

	Params::NiagaraClipboardEditorScriptingUtilities_TryGetLocalValueAsFloat Parms{};

	Parms.InInput = InInput;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bOutSucceeded != nullptr)
		*bOutSucceeded = Parms.bOutSucceeded;

	if (OutValue != nullptr)
		*OutValue = Parms.OutValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.TryGetLocalValueAsInt
// (Final, RequiredAPI, Native, Static, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// class UNiagaraClipboardFunctionInput*   InInput                                                (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bOutSucceeded                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   OutValue                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UNiagaraClipboardEditorScriptingUtilities::TryGetLocalValueAsInt(const class UNiagaraClipboardFunctionInput* InInput, bool* bOutSucceeded, int32* OutValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "TryGetLocalValueAsInt");

	Params::NiagaraClipboardEditorScriptingUtilities_TryGetLocalValueAsInt Parms{};

	Parms.InInput = InInput;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bOutSucceeded != nullptr)
		*bOutSucceeded = Parms.bOutSucceeded;

	if (OutValue != nullptr)
		*OutValue = Parms.OutValue;
}


// Function NiagaraEditor.NiagaraClipboardEditorScriptingUtilities.TrySetLocalValueAsInt
// (Final, RequiredAPI, Native, Static, Public, HasOutParams, BlueprintCallable, BlueprintPure)
// Parameters:
// class UNiagaraClipboardFunctionInput*   InInput                                                (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bOutSucceeded                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   InValue                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLooseTyping                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UNiagaraClipboardEditorScriptingUtilities::TrySetLocalValueAsInt(class UNiagaraClipboardFunctionInput* InInput, bool* bOutSucceeded, int32 InValue, bool bLooseTyping)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("NiagaraClipboardEditorScriptingUtilities", "TrySetLocalValueAsInt");

	Params::NiagaraClipboardEditorScriptingUtilities_TrySetLocalValueAsInt Parms{};

	Parms.InInput = InInput;
	Parms.InValue = InValue;
	Parms.bLooseTyping = bLooseTyping;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bOutSucceeded != nullptr)
		*bOutSucceeded = Parms.bOutSucceeded;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsBool
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UNiagaraPythonScriptModuleInput::AsBool() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsBool");

	Params::NiagaraPythonScriptModuleInput_AsBool Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsColor
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FLinearColor UNiagaraPythonScriptModuleInput::AsColor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsColor");

	Params::NiagaraPythonScriptModuleInput_AsColor Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsEnum
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UNiagaraPythonScriptModuleInput::AsEnum() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsEnum");

	Params::NiagaraPythonScriptModuleInput_AsEnum Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsFloat
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UNiagaraPythonScriptModuleInput::AsFloat() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsFloat");

	Params::NiagaraPythonScriptModuleInput_AsFloat Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsInt
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UNiagaraPythonScriptModuleInput::AsInt() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsInt");

	Params::NiagaraPythonScriptModuleInput_AsInt Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsLinkedValue
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UNiagaraPythonScriptModuleInput::AsLinkedValue() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsLinkedValue");

	Params::NiagaraPythonScriptModuleInput_AsLinkedValue Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsQuat
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FQuat                            ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FQuat UNiagaraPythonScriptModuleInput::AsQuat() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsQuat");

	Params::NiagaraPythonScriptModuleInput_AsQuat Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsVec2
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector2D                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector2D UNiagaraPythonScriptModuleInput::AsVec2() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsVec2");

	Params::NiagaraPythonScriptModuleInput_AsVec2 Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsVec3
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector UNiagaraPythonScriptModuleInput::AsVec3() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsVec3");

	Params::NiagaraPythonScriptModuleInput_AsVec3 Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.AsVec4
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector4                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector4 UNiagaraPythonScriptModuleInput::AsVec4() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "AsVec4");

	Params::NiagaraPythonScriptModuleInput_AsVec4 Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.IsLinkedValue
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UNiagaraPythonScriptModuleInput::IsLinkedValue() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "IsLinkedValue");

	Params::NiagaraPythonScriptModuleInput_IsLinkedValue Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.IsLocalValue
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UNiagaraPythonScriptModuleInput::IsLocalValue() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "IsLocalValue");

	Params::NiagaraPythonScriptModuleInput_IsLocalValue Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonScriptModuleInput.IsSet
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UNiagaraPythonScriptModuleInput::IsSet() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonScriptModuleInput", "IsSet");

	Params::NiagaraPythonScriptModuleInput_IsSet Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.GetOldInput
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraPythonScriptModuleInput*  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraPythonScriptModuleInput* UUpgradeNiagaraScriptResults::GetOldInput(const class FString& InputName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "GetOldInput");

	Params::UpgradeNiagaraScriptResults_GetOldInput Parms{};

	Parms.InputName = std::move(InputName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.ResetToDefault
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::ResetToDefault(const class FString& InputName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "ResetToDefault");

	Params::UpgradeNiagaraScriptResults_ResetToDefault Parms{};

	Parms.InputName = std::move(InputName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetBoolInput
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    Value                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetBoolInput(const class FString& InputName, bool Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetBoolInput");

	Params::UpgradeNiagaraScriptResults_SetBoolInput Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = Value;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetColorInput
// (Final, RequiredAPI, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FLinearColor                     Value                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetColorInput(const class FString& InputName, const struct FLinearColor& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetColorInput");

	Params::UpgradeNiagaraScriptResults_SetColorInput Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetEnumInput
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           Value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetEnumInput(const class FString& InputName, const class FString& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetEnumInput");

	Params::UpgradeNiagaraScriptResults_SetEnumInput Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetFloatInput
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   Value                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetFloatInput(const class FString& InputName, float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetFloatInput");

	Params::UpgradeNiagaraScriptResults_SetFloatInput Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = Value;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetIntInput
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   Value                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetIntInput(const class FString& InputName, int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetIntInput");

	Params::UpgradeNiagaraScriptResults_SetIntInput Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = Value;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetLinkedInput
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           Value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetLinkedInput(const class FString& InputName, const class FString& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetLinkedInput");

	Params::UpgradeNiagaraScriptResults_SetLinkedInput Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetNewInput
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraPythonScriptModuleInput*  Value                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetNewInput(const class FString& InputName, class UNiagaraPythonScriptModuleInput* Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetNewInput");

	Params::UpgradeNiagaraScriptResults_SetNewInput Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = Value;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetQuatInput
// (Final, RequiredAPI, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FQuat                            Value                                                  (Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetQuatInput(const class FString& InputName, const struct FQuat& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetQuatInput");

	Params::UpgradeNiagaraScriptResults_SetQuatInput Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetVec2Input
// (Final, RequiredAPI, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector2D                        Value                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetVec2Input(const class FString& InputName, const struct FVector2D& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetVec2Input");

	Params::UpgradeNiagaraScriptResults_SetVec2Input Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetVec3Input
// (Final, RequiredAPI, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector                          Value                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetVec3Input(const class FString& InputName, const struct FVector& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetVec3Input");

	Params::UpgradeNiagaraScriptResults_SetVec3Input Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.UpgradeNiagaraScriptResults.SetVec4Input
// (Final, RequiredAPI, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// class FString                           InputName                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FVector4                         Value                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UUpgradeNiagaraScriptResults::SetVec4Input(const class FString& InputName, const struct FVector4& Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UpgradeNiagaraScriptResults", "SetVec4Input");

	Params::UpgradeNiagaraScriptResults_SetVec4Input Parms{};

	Parms.InputName = std::move(InputName);
	Parms.Value = std::move(Value);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.NiagaraPythonEmitter.GetObject
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UNiagaraEmitter*                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraEmitter* UNiagaraPythonEmitter::GetObject()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonEmitter", "GetObject");

	Params::NiagaraPythonEmitter_GetObject Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonEmitter.SetProperties
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// struct FVersionedNiagaraEmitterData     Data                                                   (Parm, NativeAccessSpecifierPublic)

void UNiagaraPythonEmitter::SetProperties(const struct FVersionedNiagaraEmitterData& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonEmitter", "SetProperties");

	Params::NiagaraPythonEmitter_SetProperties Parms{};

	Parms.Data = std::move(Data);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function NiagaraEditor.NiagaraPythonEmitter.GetModule
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ModuleName                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UNiagaraPythonModule*             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UNiagaraPythonModule* UNiagaraPythonEmitter::GetModule(const class FString& ModuleName) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonEmitter", "GetModule");

	Params::NiagaraPythonEmitter_GetModule Parms{};

	Parms.ModuleName = std::move(ModuleName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonEmitter.GetModules
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// TArray<class UNiagaraPythonModule*>     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class UNiagaraPythonModule*> UNiagaraPythonEmitter::GetModules() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonEmitter", "GetModules");

	Params::NiagaraPythonEmitter_GetModules Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonEmitter.GetProperties
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVersionedNiagaraEmitterData     ReturnValue                                            (Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)

struct FVersionedNiagaraEmitterData UNiagaraPythonEmitter::GetProperties() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonEmitter", "GetProperties");

	Params::NiagaraPythonEmitter_GetProperties Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function NiagaraEditor.NiagaraPythonEmitter.HasModule
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ModuleName                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UNiagaraPythonEmitter::HasModule(const class FString& ModuleName) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NiagaraPythonEmitter", "HasModule");

	Params::NiagaraPythonEmitter_HasModule Parms{};

	Parms.ModuleName = std::move(ModuleName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

