#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: note_progressor_device

#include "Basic.hpp"

#include "patchwork_device_classes.hpp"


namespace SDK
{

// VerseClass note_progressor_device.note_progressor_device
// 0x0000 (0x00D0 - 0x00D0)
class Unote_progressor_device final : public Upatchwork_device
{
public:
	void _Block();
	void _InitCDO();
	void _InitInstance();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"note_progressor_device">();
	}
	static class Unote_progressor_device* GetDefaultObj()
	{
		return GetDefaultObjImpl<Unote_progressor_device>();
	}
};

}

