#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: perception_trigger_device

#include "Basic.hpp"

#include "perception_trigger_device_classes.hpp"
#include "perception_trigger_device_parameters.hpp"


namespace SDK
{

// Function perception_trigger_device.perception_trigger_device.$Block
// ()

void Uperception_trigger_device::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("perception_trigger_device", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function perception_trigger_device.perception_trigger_device.$InitCDO
// (HasDefaults)

void Uperception_trigger_device::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("perception_trigger_device", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function perception_trigger_device.perception_trigger_device.$InitInstance
// ()

void Uperception_trigger_device::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("perception_trigger_device", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}

}

