#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PinnedCommandList

#include "Basic.hpp"

#include "PinnedCommandList_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class PinnedCommandList.PinnedCommandListSettings
// 0x0010 (0x0040 - 0x0030)
class UPinnedCommandListSettings final : public UObject
{
public:
	TArray<struct FPinnedCommandListContext>      Contexts;                                          // 0x0030(0x0010)(ZeroConstructor, Config, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PinnedCommandListSettings">();
	}
	static class UPinnedCommandListSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPinnedCommandListSettings>();
	}
};

}

