#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: player_counter_device

#include "Basic.hpp"

#include "player_counter_device_classes.hpp"
#include "player_counter_device_parameters.hpp"


namespace SDK
{

// Function player_counter_device.player_counter_device.$Block
// ()

void Uplayer_counter_device::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_counter_device.player_counter_device.$InitCDO
// (HasDefaults)

void Uplayer_counter_device::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_counter_device.player_counter_device.$InitInstance
// ()

void Uplayer_counter_device::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RCompareToTarget
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RCompareToTarget(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RCompareToTarget");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RCompareToTarget Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RDecrementTargetCount
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RDecrementTargetCount(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RDecrementTargetCount");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RDecrementTargetCount Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RDisable
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RDisable(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RDisable");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RDisable Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_REnable
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_REnable(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_REnable");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_REnable Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RGetCount
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int64 Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RGetCount(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RGetCount");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RGetCount Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RGetTargetCount
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int64                                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int64 Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RGetTargetCount(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RGetTargetCount");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RGetTargetCount Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RHideInfoPanel
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RHideInfoPanel(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RHideInfoPanel");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RHideInfoPanel Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIncrementTargetCount
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIncrementTargetCount(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIncrementTargetCount");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIncrementTargetCount Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsCounted_L_Nagent_R
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class USimulation_agent*                __verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
// TOptional<EVerseTrue>                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

TOptional<EVerseTrue> Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsCounted_L_Nagent_R(class USimulation_agent* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsCounted_L_Nagent_R");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsCounted_L_Nagent_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsPassingTest
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TOptional<EVerseTrue>                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

TOptional<EVerseTrue> Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsPassingTest(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsPassingTest");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsPassingTest Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsShowingInfoPanel
// (Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TOptional<EVerseTrue>                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

TOptional<EVerseTrue> Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsShowingInfoPanel(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsShowingInfoPanel");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RIsShowingInfoPanel Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RRegister_L_Nagent_R
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// class USimulation_agent*                __verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RRegister_L_Nagent_R(class USimulation_agent* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RRegister_L_Nagent_R");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RRegister_L_Nagent_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RReset
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RReset(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RReset");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RReset Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RSetTargetCount_L_Nint_R
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// int64                                   __verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RSetTargetCount_L_Nint_R(int64 __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RSetTargetCount_L_Nint_R");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RSetTargetCount_L_Nint_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RShowInfoPanel
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RShowInfoPanel(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RShowInfoPanel");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RShowInfoPanel Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RTransmitForAllCounted
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RTransmitForAllCounted(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RTransmitForAllCounted");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RTransmitForAllCounted Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RUnregister_L_Nagent_R
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// class USimulation_agent*                __verse_0xB2CDDD72_Argument                            (ExportObject, Parm, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RUnregister_L_Nagent_R(class USimulation_agent* __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RUnregister_L_Nagent_R");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RUnregister_L_Nagent_R Parms{};

	Parms.__verse_0xB2CDDD72_Argument = __verse_0xB2CDDD72_Argument;

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_counter_device.player_counter_device._L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RUnregisterAll
// (Public, HasDefaults, BlueprintCallable)
// Parameters:
// struct player_counter_device::Ftuple_L_R__verse_0xB2CDDD72_Argument                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_counter_device::_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RUnregisterAll(const struct player_counter_device::Ftuple_L_R& __verse_0xB2CDDD72_Argument)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_counter_device", "_L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RUnregisterAll");

	Params::player_counter_device__L_2fFortnite_2ecom_2fDevices_2fplayer__counter__device_N_RUnregisterAll Parms{};

	Parms.__verse_0xB2CDDD72_Argument = std::move(__verse_0xB2CDDD72_Argument);

	UObject::ProcessEvent(Func, &Parms);
}

}

