#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SourceCodeAccess

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class SourceCodeAccess.SourceCodeAccessSettings
// 0x0010 (0x0040 - 0x0030)
class USourceCodeAccessSettings final : public UObject
{
public:
	class FString                                 PreferredAccessor;                                 // 0x0030(0x0010)(Edit, ZeroConstructor, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SourceCodeAccessSettings">();
	}
	static class USourceCodeAccessSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<USourceCodeAccessSettings>();
	}
};

}

