#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SparksAlbumArtRuntime

#include "Basic.hpp"


namespace SDK::Params
{

// Function SparksAlbumArtRuntime.SparksAlbumArtManager.RequestAlbumArt
// 0x0024 (0x0024 - 0x0000)
struct SparksAlbumArtManager_RequestAlbumArt final
{
public:
	class FName                                   SongShortName;                                     // 0x0000(0x000C)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class FName& SongShortName, TSoftObjectPtr<class UTexture2D>& AlbumArt, bool bWasSuccessful)> OnRequestFinished;                                 // 0x000C(0x0014)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

}

