#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TabHUDOptions_New

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TabHUDOptions_New.TabHUDOptions_New_C
// 0x0008 (0x05C8 - 0x05C0)
class UTabHUDOptions_New_C final : public UFortTabHUDOptions_TempNew
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void CenterOnTab();
	void ExecuteUbergraph_TabHUDOptions_New(int32 EntryPoint);
	void SettingValueChanged(double Value);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TabHUDOptions_New_C">();
	}
	static class UTabHUDOptions_New_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTabHUDOptions_New_C>();
	}
};

}

