#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: timer_device

#include "Basic.hpp"


namespace SDK
{

// VerseStruct timer_device.tuple_L_R
// 0x0001 (0x0001 - 0x0000)
struct timer_device::Ftuple_L_R final
{
public:
	uint8                                         _StructPaddingDummy;                               // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// VerseStruct timer_device.tuple_Lfloat_Magent_R
// 0x0010 (0x0010 - 0x0000)
struct Ftuple_Lfloat_Magent_R final
{
public:
	double                                        __verse_0x18E3F084_Elem0;                          // 0x0000(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USimulation_agent*                      __verse_0x7D844C3C_Elem1;                          // 0x0008(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
};

}

