#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UnrealEdMessages

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// ScriptStruct UnrealEdMessages.AssetEditorRequestOpenAsset
// 0x0010 (0x0010 - 0x0000)
struct FAssetEditorRequestOpenAsset final
{
public:
	class FString                                 AssetName;                                         // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct UnrealEdMessages.FileServerReady
// 0x0020 (0x0020 - 0x0000)
struct FFileServerReady final
{
public:
	TArray<class FString>                         AddressList;                                       // 0x0000(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	struct FGuid                                  InstanceId;                                        // 0x0010(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

