#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UnrealEngineExperimental_0

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_classes.hpp"
#include "VerseColors_structs.hpp"
#include "UnrealEngineExperimental_0_structs.hpp"


namespace SDK
{

// VerseClass UnrealEngineExperimental.Curves_editable_curve
// 0x0000 (0x00F0 - 0x00F0)
class UCurves_editable_curve final : public UCurveFloat
{
public:
	void _Block();
	void _InitCDO();
	void _InitInstance();
	double _L_2fUnrealEngine_2ecom_2fTemporary_2fCurves_2feditable__curve_N_REvaluate_L_Nfloat_R(double __verse_0xB2CDDD72_Argument);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Curves_editable_curve">();
	}
	static class UCurves_editable_curve* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCurves_editable_curve>();
	}
};

// VerseClass UnrealEngineExperimental.Testing_test_reporter
// 0x0068 (0x0098 - 0x0030)
class UTesting_test_reporter final : public UObject
{
public:
	FVerseStringProperty_                         __verse_0x38D9A616_Name;                           // 0x0030(0x0010)(InstancedReference, HasGetValueTypeHash)
	EDiagnostics_log_level                        __verse_0x540F3253_DefaultLevel;                   // 0x0040(0x0001)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x57];                                      // 0x0041(0x0057)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void _Block();
	void _InitCDO();
	void _InitInstance();
	TArray<FVerseStringProperty_> _L_2fUnrealEngine_2ecom_2fTemporary_2fTesting_2ftest__reporter_N_RGetSummaryStrings_L_N_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R(TOptional<EDiagnostics_log_level> __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fTesting_2ftest__reporter_N_RLog_L_N_Kchar_M_N_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R(const struct UnrealEngineExperimental_0::Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fTesting_2ftest__reporter_N_RPrintSummary_L_N_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R(TOptional<EDiagnostics_log_level> __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fTesting_2ftest__reporter_N_RReportTestFailed_L_N_Kchar_M_N_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_N_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R(const struct Ftuple_L_Kchar_M_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fTesting_2ftest__reporter_N_RReportTestPassed_L_N_Kchar_M_N_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_N_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R(const struct Ftuple_L_Kchar_M_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fTesting_2ftest__reporter_N_RReportTestResult_L_N_Kchar_M_Ntest__result_M_N_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_N_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R(const struct UnrealEngineExperimental_0::Ftuple_L_Kchar_Mtest__result_M_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fTesting_2ftest__reporter_N_RReportTestSkipped_L_N_Kchar_M_N_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_N_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R(const struct Ftuple_L_Kchar_M_QCategory_N_Kchar_20_3d_20_2e_2e_2e_M_QSubCategory_N_Kchar_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fTesting_2ftest__reporter_N_RReset(const struct UnrealEngineExperimental_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Testing_test_reporter">();
	}
	static class UTesting_test_reporter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTesting_test_reporter>();
	}
};

// VerseClass UnrealEngineExperimental.Diagnostics
// 0x0038 (0x0068 - 0x0030)
class UDiagnostics final : public UObject
{
public:
	struct FColors_color                          __verse_0x57D963B0_DefaultDebugDrawColor;          // 0x0030(0x0018)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor)
	EDiagnostics_debug_draw_duration_policy       __verse_0xBB769F64_DefaultDebugDrawDurationPolicy; // 0x0048(0x0001)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        __verse_0x455A65A8_DefaultDebugDrawDuration;       // 0x0050(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        __verse_0xD30692C9_DefaultDebugDrawSize;           // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        __verse_0xA45DC86B_DefaultDebugDrawThickness;      // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void _InitCDO();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Diagnostics">();
	}
	static class UDiagnostics* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDiagnostics>();
	}
};

// VerseClass UnrealEngineExperimental.Diagnostics_debug_draw_channel
// 0x0000 (0x0030 - 0x0030)
class UDiagnostics_debug_draw_channel final : public UObject
{
public:
	void _Block();
	void _InitCDO();
	void _InitInstance();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Diagnostics_debug_draw_channel">();
	}
	static class UDiagnostics_debug_draw_channel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDiagnostics_debug_draw_channel>();
	}
};

// VerseClass UnrealEngineExperimental.Diagnostics_debug_draw
// 0x0018 (0x0048 - 0x0030)
class UDiagnostics_debug_draw final : public UObject
{
public:
	class UClass*                                 __verse_0xFAE6EE9E_Channel;                        // 0x0030(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	uint8                                         Pad_38[0x10];                                      // 0x0038(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void _Block();
	void _InitCDO();
	void _InitInstance();
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RClear(const struct UnrealEngineExperimental_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RClearChannel(const struct UnrealEngineExperimental_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RDrawArrow_L_Nvector3_M_Nvector3_M_N_QArrowSize_Nfloat_20_3d_20_2e_2e_2e_M_N_QColor_Ncolor_20_3d_20_2e_2e_2e_M_N_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_N_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R(const struct Ftuple_Lvector3_Mvector3_M_QArrowSize_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RDrawBox_L_Nvector3_M_Nrotation_M_N_QExtent_Nvector3_20_3d_20_2e_2e_2e_M_N_QColor_Ncolor_20_3d_20_2e_2e_2e_M_N_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_N_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R(const struct Ftuple_Lvector3_Mrotation_M_QExtent_Nvector3_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RDrawCapsule_L_Nvector3_M_Nrotation_M_N_QHeight_Nfloat_20_3d_20_2e_2e_2e_M_N_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_N_QColor_Ncolor_20_3d_20_2e_2e_2e_M_N_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_N_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R(const struct Ftuple_Lvector3_Mrotation_M_QHeight_Nfloat_20_3d_20_2e_2e_2e_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RDrawCone_L_Nvector3_M_Nvector3_M_N_QHeight_Nfloat_20_3d_20_2e_2e_2e_M_N_QNumSides_Nint_20_3d_20_2e_2e_2e_M_N_QAngleWidthRadians_Nfloat_20_3d_20_2e_2e_2e_M_N_QAngleHeightRadians_Nfloat_20_3d_20_2e_2e_2e_M_N_QColor_Ncolor_20_3d_20_2e_2e_2e_M_N_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_N_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R(const struct Ftuple_Lvector3_Mvector3_M_QHeight_Nfloat_20_3d_20_2e_2e_2e_M_QNumSides_Nint_20_3d_20_2e_2e_2e_M_QAngleWidthRadians_Nfloat_20_3d_20_2e_2e_2e_M_QAngleHeightRadians_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RDrawCylinder_L_Nvector3_M_Nvector3_M_N_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_N_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_N_QColor_Ncolor_20_3d_20_2e_2e_2e_M_N_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_N_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R(const struct Ftuple_Lvector3_Mvector3_M_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RDrawLine_L_Nvector3_M_Nvector3_M_N_QColor_Ncolor_20_3d_20_2e_2e_2e_M_N_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_N_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R(const struct Ftuple_Lvector3_Mvector3_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RDrawPoint_L_Nvector3_M_N_QColor_Ncolor_20_3d_20_2e_2e_2e_M_N_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_N_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R(const struct Ftuple_Lvector3_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RDrawSphere_L_Nvector3_M_N_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_N_QColor_Ncolor_20_3d_20_2e_2e_2e_M_N_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_N_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_N_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_N_QDuration_Nfloat_20_3d_20_2e_2e_2e_R(const struct UnrealEngineExperimental_0::Ftuple_Lvector3_M_QRadius_Nfloat_20_3d_20_2e_2e_2e_M_QColor_Ncolor_20_3d_20_2e_2e_2e_M_QNumSegments_Nint_20_3d_20_2e_2e_2e_M_QThickness_Nfloat_20_3d_20_2e_2e_2e_M_QDrawDurationPolicy_Ndebug__draw__duration__policy_20_3d_20_2e_2e_2e_M_QDuration_Nfloat_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RHideChannel(const struct UnrealEngineExperimental_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2fdebug__draw_N_RShowChannel(const struct UnrealEngineExperimental_0::Ftuple_L_R& __verse_0xB2CDDD72_Argument);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Diagnostics_debug_draw">();
	}
	static class UDiagnostics_debug_draw* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDiagnostics_debug_draw>();
	}
};

// VerseClass UnrealEngineExperimental.Diagnostics_log
// 0x0010 (0x0040 - 0x0030)
class UDiagnostics_log : public UObject
{
public:
	class UClass*                                 __verse_0xFAE6EE9E_Channel;                        // 0x0030(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EDiagnostics_log_level                        __verse_0x540F3253_DefaultLevel;                   // 0x0038(0x0001)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void _Block();
	void _InitCDO();
	void _InitInstance();
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2flog_N_RPrint_L_N_Kchar_M_N_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R(const struct UnrealEngineExperimental_0::Ftuple_L_Kchar_M_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R& __verse_0xB2CDDD72_Argument);
	void _L_2fUnrealEngine_2ecom_2fTemporary_2fDiagnostics_2flog_N_RPrintCallStack_L_N_QLevel_Nlog__level_20_3d_20_2e_2e_2e_R(TOptional<EDiagnostics_log_level> __verse_0xB2CDDD72_Argument);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Diagnostics_log">();
	}
	static class UDiagnostics_log* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDiagnostics_log>();
	}
};

// VerseClass UnrealEngineExperimental.Diagnostics_log_channel
// 0x0000 (0x0030 - 0x0030)
class UDiagnostics_log_channel : public UObject
{
public:
	void _Block();
	void _InitCDO();
	void _InitInstance();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Diagnostics_log_channel">();
	}
	static class UDiagnostics_log_channel* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDiagnostics_log_channel>();
	}
};

}

