#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseWorldPartition

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class VerseWorldPartition.VerseDataLayerManagerBase
// 0x0000 (0x0030 - 0x0030)
class UVerseDataLayerManagerBase : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"VerseDataLayerManagerBase">();
	}
	static class UVerseDataLayerManagerBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVerseDataLayerManagerBase>();
	}
};

}

