#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseDevices_0

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"


namespace SDK
{

// Enum VerseDevices.EScriptPropertyOverridesVersion
// NumValues: 0x0006
enum class EScriptPropertyOverridesVersion : uint32
{
	Initial                                  = 0,
	UsingSoftObjectPathSerialization         = 1,
	ObjectClassSerialization                 = 2,
	LatestPlusOne                            = 3,
	Latest                                   = 2,
	EScriptPropertyOverridesVersion_MAX      = 4,
};

// ScriptStruct VerseDevices.PlaylistOptionScriptValue
// 0x0008 (0x00B8 - 0x00B0)
struct FPlaylistOptionScriptValue final : public FPlaylistOptionValue
{
public:
	TSubclassOf<class UVerseCreativeDevice>       Value;                                             // 0x00B0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct VerseDevices.VerseDeviceFunctionPayload
// 0x0008 (0x0008 - 0x0000)
struct FVerseDeviceFunctionPayload final
{
public:
	class AController*                            Instigator;                                        // 0x0000(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

