#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseFramework_test_device_log

#include "Basic.hpp"

#include "VerseFramework_test_device_log_classes.hpp"


namespace SDK
{

// Function VerseFramework_test_device_log.test_device_log.$Block
// ()

void Utest_device_log::_Block()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("test_device_log", "$Block");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseFramework_test_device_log.test_device_log.$InitCDO
// ()

void Utest_device_log::_InitCDO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("test_device_log", "$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseFramework_test_device_log.test_device_log.$InitInstance
// ()

void Utest_device_log::_InitInstance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("test_device_log", "$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}

}

