#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VirtualizationEditor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class VirtualizationEditor.CheckForVirtualizedContentCommandlet
// 0x0000 (0x0088 - 0x0088)
class UCheckForVirtualizedContentCommandlet final : public UCommandlet
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CheckForVirtualizedContentCommandlet">();
	}
	static class UCheckForVirtualizedContentCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCheckForVirtualizedContentCommandlet>();
	}
};

// Class VirtualizationEditor.GeneratePayloadManifestCommandlet
// 0x0008 (0x0090 - 0x0088)
class UGeneratePayloadManifestCommandlet final : public UCommandlet
{
public:
	uint8                                         Pad_88[0x8];                                       // 0x0088(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"GeneratePayloadManifestCommandlet">();
	}
	static class UGeneratePayloadManifestCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGeneratePayloadManifestCommandlet>();
	}
};

// Class VirtualizationEditor.PrecachePayloadsCommandlet
// 0x0000 (0x0088 - 0x0088)
class UPrecachePayloadsCommandlet final : public UCommandlet
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PrecachePayloadsCommandlet">();
	}
	static class UPrecachePayloadsCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrecachePayloadsCommandlet>();
	}
};

// Class VirtualizationEditor.RehydrateProjectCommandlet
// 0x0008 (0x0090 - 0x0088)
class URehydrateProjectCommandlet final : public UCommandlet
{
public:
	uint8                                         Pad_88[0x8];                                       // 0x0088(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"RehydrateProjectCommandlet">();
	}
	static class URehydrateProjectCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<URehydrateProjectCommandlet>();
	}
};

// Class VirtualizationEditor.ValidateVirtualizedContentCommandlet
// 0x0000 (0x0088 - 0x0088)
class UValidateVirtualizedContentCommandlet final : public UCommandlet
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ValidateVirtualizedContentCommandlet">();
	}
	static class UValidateVirtualizedContentCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UValidateVirtualizedContentCommandlet>();
	}
};

// Class VirtualizationEditor.VirtualizeProjectCommandlet
// 0x0008 (0x0090 - 0x0088)
class UVirtualizeProjectCommandlet final : public UCommandlet
{
public:
	uint8                                         Pad_88[0x8];                                       // 0x0088(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"VirtualizeProjectCommandlet">();
	}
	static class UVirtualizeProjectCommandlet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVirtualizeProjectCommandlet>();
	}
};

}

